// Test definitions. Do NOT edit this file!
#include <tuple>
#include <vector>
#include <algorithm>

#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch.hpp"

#include "student.hpp" // student implementations

// =====================
// tests for exercise 4.1
// ---------------------
TEST_CASE("Ex41", "[example]")
{
    REQUIRE(power(4, 2) == 16);
    REQUIRE(power(4, -2) == 0.0625);
    REQUIRE(power(4, 0) == 1);
}

// =====================
// tests for exercise 4.2
// ---------------------
TEST_CASE("Ex42", "[example]")
{
    REQUIRE(fakult(0) == 1);
    REQUIRE(fakult(1) == 1);
    REQUIRE(fakult(7) == 5040);
    REQUIRE(fakult(-7) == -1);
}

// =====================
// tests for exercise 4.3
// ---------------------
TEST_CASE("Ex43", "[example]")
{   
    int n1 = 0;
    int n2 = 1;
    int n3 = 7;
    int n4 = -7;
    REQUIRE(fak(n1) == 1);
    REQUIRE(fak(n2) == 1);
    REQUIRE(fak(n3) == 5040);
    REQUIRE(fak(n4) == -1);}
/*
// =====================
// tests for exercise 4.4
// ---------------------
TEST_CASE("Ex44", "[example]")
{
    REQUIRE(max(42,7) == 42);
    REQUIRE(max(-42,7) == 7);
}

// =====================
// tests for exercise 4.6
// ---------------------
TEST_CASE("Ex46", "[example]")
{
    REQUIRE(maximum(42,7) == 42);
    REQUIRE(maximum(-42,7) == 7);
}

// =====================
// tests for exercise 4.7
// ---------------------
TEST_CASE("Ex47", "[example]")
{
    vector<int> vi;
    vi.push_back(-5);
    vi.push_back(3);
    vi.push_back(7);
    REQUIRE(vectorMax(vi) == 7);
}
*/
